defaults:
  - task: lbf/lbf_7x7_nolevels # overcooked-v1/cramped_room # task configs
  - global_heldout_settings # defines the heldout_set variable
  - global_heldout_br_generated # best responses to global heldout set
  # - global_validation_settings # defines the heldout_set variable
  - hydra: hydra_simple
  - _self_

# Set best response set to heldout set
best_response_set: ${heldout_set}

ENV_NAME: ${task.ENV_NAME}
ENV_KWARGS: ${task.ENV_KWARGS}
TASK_NAME: ${task.TASK_NAME}

label: ""
name: ${TASK_NAME}/heldout_xp_matrix/${label}

xp_matrix_outputs:
  save_heatmap: true
