defaults:
  - task: lbf # task configs
  - global_validation_settings # validation partners for hyperparameter tuning
  - hydra: hydra_simple
  - _self_

ENV_NAME: ${task.ENV_NAME}
ENV_KWARGS: ${task.ENV_KWARGS}
TASK_NAME: ${task.TASK_NAME}

label: ""
name: ${TASK_NAME}/validation_ego_eval/${label}

ego_agent:
  path: null
  actor_type: s5
  idx_list: null
  test_mode: true
